// Generated by CoffeeScript 1.8.0
(function() {
  var auth, fs, handler, http, noteDir, parseCookies, path, savePage, search, searchAll, serveIndex, serveLogin, servePage, templater, url;

  http = require('http');

  fs = require('fs');

  path = require('path');

  url = require('url');

  noteDir = (process.env.NOTEDIR || 'notes') + '/';

  parseCookies = function(request) {
    var list, rc;
    list = {};
    rc = request.headers.cookie;
    rc && rc.split(";").forEach(function(cookie) {
      var parts;
      parts = cookie.split("=");
      list[parts.shift().trim()] = unescape(parts.join("="));
    });
    return list;
  };

  auth = function(cookie) {
    if (!process.env.NOTEDPASS) {
      return true;
    }
    if (cookie.notedpass === process.env.NOTEDPASS) {
      return true;
    }
  };

  handler = function(req, res) {
    req.parsed = url.parse(req.url, true);
    if (!auth(parseCookies(req))) {
      return serveLogin(req, res);
    }
    if (['favicon.ico'].indexOf(path.basename(req.url)) > -1) {
      res.writeHead(404);
      return res.end();
    }
    if (req.url === '/') {
      return serveIndex('html', req, res);
    }
    if (req.url === '/index.js') {
      return serveIndex('js', req, res);
    }
    if (req.parsed.pathname === '/search') {
      return searchAll(req, res);
    }
    if (req.url.split('/')[1] !== 'api') {
      return serveIndex('html', req, res);
    }
    req.url.replace(/\./g, '');
    req.url.replace(/api\//, '');
    if (req.method === 'PUT') {
      return savePage(req, res);
    }
    if (req.method === 'GET') {
      return servePage(req, res);
    }
  };

  serveIndex = function(ext, req, res) {
    return fs.createReadStream("./index." + ext).pipe(res);
  };

  serveLogin = function(req, res) {
    res.writeHead(403);
    return fs.createReadStream("./login.html").pipe(res);
  };

  servePage = function(req, res) {
    var reader;
    reader = fs.createReadStream(noteDir + path.basename(req.url));
    reader.on('error', function(err) {
      return res.end("");
    });
    return reader.pipe(res);
  };

  savePage = function(req, res) {
    return req.pipe(fs.createWriteStream(noteDir + path.basename(req.url))).on('close', function() {
      return res.end();
    });
  };

  searchAll = function(req, res) {
    return fs.readdir(noteDir, function(err, files) {
      var matches;
      matches = files.filter(search(req.parsed.query.s));
      if (matches.length < 1) {
        res.writeHead(404);
      }
      if (req.headers.accept.match('application/json')) {
        res.end(JSON.stringify(matches));
      }
      return fs.readFile('search.html', function(err, content) {
        if (matches.length < 1) {
          return res.end(content);
        }
        return res.end(content.toString().replace('no matches', matches.map(templater("<a href=foobar>foobar</a>")).join('</p><p>')));
      });
    });
  };

  search = function(term) {
    return function(file) {
      if (fs.readFileSync(path.join(noteDir, file)).toString().match(term)) {
        return true;
      }
      return false;
    };
  };

  templater = function(template) {
    return function(insert) {
      return template.replace(/foobar/g, insert);
    };
  };

  http.createServer(handler).listen(process.env.PORT || 3000);

}).call(this);
